---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.11.131
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ubuntu
